<?xml version="1.0"?>
<package format="3">
  <name>hack_to_the_future_hvac</name>
  <version>0.1.0</version>
  <description>ROS 2 HVAC simulator stack for Hack to the Future.</description>
  <maintainer email="devnull@example.com">Codex</maintainer>
  <license>EPL-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>diagnostic_msgs</depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <depend>muto_msgs</depend>
  <depend>rclpy</depend>
  <depend>std_msgs</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
